### ISSUE TITLE
Request for a couple of examples

### ISSUE THREAD

**Issue by si2030** [buttonwoodcx/bcx-aurelia-dnd#11]
Hi there,

Really good to see something that actually has documentation that can be followed and built upon.. thanks.

Wondering if you could create an example of grid snap or snap to a position if you are close etc.

(I found an example of the other item I wanted..
Simon - si2030

**Comment by huochunpeng** [comment]
Sure. Will do.

**Comment by si2030** [comment]
Super... :)

**Comment by huochunpeng** [comment]
https://buttonwoodcx.github.io/doc-bcx-aurelia-dnd/#/e8-move-and-resize-plus-snap

**Comment by huochunpeng** [comment]
The test coverage on snapToEdge is not good enough, I am just too lazy to write more test code...

**Comment by si2030** [comment]
Just noticed you did this.. I am downloading it now.. Thankyou

**Comment by huochunpeng** [comment]
If that's sufficient, pls close this PR.

**Comment by si2030** [comment]
The fact you did this is great. Thank you.  I am crawling at the moment however I may ask you questions regarding the edge snap if I cant nut it out.. thats a whiles a way though.
