### ISSUE TITLE
Possible? Move source out of target

### ISSUE THREAD

**Issue by seriouz** [buttonwoodcx/bcx-aurelia-dnd#14]
Is it possible to drag an source out of a target, when was already dropped onto it?
Or resize a source bigger than its target.

**Comment by 3cp** [comment]
Source and target are totally independent. They don't need to have child parent relationship in DOM, nor need size limit.

To drag a source out of something, it must land somehow, you define the somewhere as another target. That is basically how multi-list reorderable-repeat was implemented.


When your source layout is bigger than its container, you need to handle it with overflow css on the container dom, bcx-aurelia-dnd does care much.

**Comment by seriouz** [comment]
Thank you!
