### ISSUE TITLE
Typescript support update

### ISSUE THREAD

**Issue by periclitor** [buttonwoodcx/bcx-aurelia-dnd#16]
I'm getting TS7051: Parameter has a name but no type. Did you mean 'arg0: Element'? in file bcx-aurelia-dnd/index.d.ts(55,23).
![image](https://user-images.githubusercontent.com/7282607/74532600-46095100-4f38-11ea-8a79-0cd0ae12ad1b.png)
I'm running Typescript 3.5.3. Can I get around  this or should it be corrected?

**Comment by 3cp** [comment]
My bad. I am surprised previous ts didn't complain about my code! Will fix soon.

**Comment by 3cp** [comment]
try v1.0.3

**Comment by periclitor** [comment]
I'll try it on Monday. Thank you!
