### ISSUE TITLE
JSDoc types can only be used inside documentation comments.

### ISSUE THREAD

**Issue by bliu886** [buttonwoodcx/bcx-aurelia-dnd#4]
I get the following error when using dnd in my aurelia project:

node_modules/bcx-aurelia-dnd/index.d.ts(55,35): error TS8020: JSDoc types can only be used inside documentation comments.

I used 'au install bcx-aurelia-dnd' to install it and am using the aurelia cli if it matters.

**Comment by huochunpeng** [comment]
Thx for reporting! I did not use TypeScript often.

Please try latest 0.4.7.

**Comment by jpcorona** [comment]
@bliu886 I changed SweetAlertArrayOptions = [string?, string?, SweetAlertType?] >>to>> SweetAlertArrayOptions = [string, string, SweetAlertType]; in line 361 sweetalert2.d.ts file (in node module folder).It works for me. but I don't know it is a proper solution.

Credits: https://github.com/sweetalert2/sweetalert2/issues/1773#issuecomment-548573328

**Comment by 3cp** [comment]
I am confused. I didn't see any TS error in an app with latest bcx-aurelia-dnd.

Can anyone share a repo to reproduce the typing error?

**Comment by anuja8275** [comment]
i m getting this issue and messed up not able to fund out can someone help me to know?
