### ISSUE TITLE
reorderable-after-reordering: How to find out which item got moved

### ISSUE THREAD

**Issue by davidtimovski** [buttonwoodcx/bcx-aurelia-dnd#7]
This isn't as much of an issue as it is a help request. Most sorting libraries give you access to the moved element/item, its previous index, and its new index in the callback that's invoked when the reordering ends. With `reorderable-after-reordering` I only get the newly reordered list so it's kind of difficult to find out which item was moved and to which new index.

Is there an easy way I can achieve this or will I have to hack some function that compares the previous and new order of the list?

**Comment by huochunpeng** [comment]
About few months ago I removed some part of the doc to cover your usage. Maybe I need to add them back, or enhance the callback.

Inspect the changes from collection observer, it got what you want.

-----
With Aurelia, you actually don't need this callback. The generic solution is to use Aurelia `BindingEngine`'s `collectionObserver`. Here is some sample code on how to do that.

```javascript
import {inject, BindingEngine} from 'aurelia-framework';
@inject(BindingEngine)
export class YourComponent {
  items = [ /* ... */ ];

  constructor(bindingEngine) {
    this.bindingEngine = bindingEngine;
  }

  attached() {
    this._subscriber = this.bindingEngine.collectionObserver(this.items).subscribe((changes) => {
      // `this.items` here is the updated array.
      // `changes` is the aurelia collection mutation, if you know what to inspect it.
    });
  }

  detached() {
    this._subscriber.dispose();
  }
}
```

> This solution catches all mutation on `items` array, no matter whether the change is triggered by `reorderable-repeat`.

> For only listening to changes triggered by `reorderable-repeat`, use "reorderable-after-reordering" callback.

**Comment by huochunpeng** [comment]
use bcx-aurelia-reorderable-repeat v1.1.0, there is 2nd argument in shape `{fromIndex, toIndex}` for single list mode.

Note only `reorderable-after-reordering="methodName"` gets the 2 arguments passed in. Not the `reorderable-after-reordering.call="method(...)"`, where arguments were provided by you explicitly.

**Comment by davidtimovski** [comment]
Wow that's great man. Feature development on call! Works perfectly, thank you!
